#!/usr/bin/perl

##//////////////////////////////////////////////////////////////////////////////
## Copyright (c) 2013, Lawrence Livermore National Security, LLC.
## Produced at the Lawrence Livermore National Laboratory.
## Written by the Greg Bronevetsky <bronevetsky1@llnl.gov> / <greg@bronevetsky.com>. 
##
## LLNL-CODE-642002
## All rights reserved.
##
## This file is part of Sight. For details, see https://e-reports-ext.llnl.gov/pdf/781752.pdf or
## https://github.com/bronevet/sight.
##
## Licensed under the GNU Lesser General Public License (Lesser GPU) Version 2.1, 
## February 1999; you may not use this file except in compliance with the License.  
## The full licence is included in file LICENCE and you may obtain a copy of the 
## License at: 
## https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
## implied. See the License for the specific language governing
## permissions and limitations under the license.
##//////////////////////////////////////////////////////////////////////////////

if(scalar(@ARGV)==0) { die "ERROR: need at least one argument to identify processes to kill"; }

my $ps = `ps -ef |grep $ENV{USER}`;
my @lines = split(/\n/, $ps);

foreach my $line (@lines)
{
	my @fields = split(/\s+/, $line);
	if($fields[1] != $$) {
		foreach my $field (@fields) {
			foreach my $killStr (@ARGV) {
				if($field =~ /$killStr/) { 
					print  "kill -9 $fields[1]\n"; 
					`kill -9 $fields[1]`; 
					next;
				}
			}
		}
	}
}
